#!/usr/bin/env node
// Generates packages/cli/src/generated/overlay-bundle.ts from the built overlay
// IIFE bundle, so the CLI can serve the overlay from memory when packaged as a
// standalone binary (no overlay.js file on disk next to the executable).
//
// Run automatically by the CLI build + `build:bin`. The disk copy is still
// preferred at runtime in dev (hot-reload), so a stale constant only affects the
// compiled binary, which always regenerates this first.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const overlayPath = resolve(here, "../packages/overlay/dist/overlay.js");
const outPath = resolve(here, "../packages/cli/src/generated/overlay-bundle.ts");

const overlay = readFileSync(overlayPath, "utf8");

const banner =
  "// AUTO-GENERATED by scripts/embed-overlay.mjs — do not edit.\n" +
  "// Regenerate with `pnpm gen:overlay` (run as part of the CLI build).\n";

const body = `${banner}export const OVERLAY_JS = ${JSON.stringify(overlay)};\n`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body);

console.log(`embed-overlay: wrote ${outPath} (${(overlay.length / 1024).toFixed(0)} KB source)`);
