import type { ThemeStyles } from "@themelab/shared"
import { reformat, type ColorFormat } from "./oklch"
import { THEME_TOKENS } from "./transpile"

const DEFAULT_NAME = "ThemeLab theme"
const DEFAULT_DESCRIPTION =
  "A shadcn theme generated by ThemeLab with light and dark semantic color tokens."

function cleanText(value: string, fallback: string, maxLength: number): string {
  const cleaned = value
    .replace(/[\u0000-\u001f\u007f-\u009f]/gu, " ")
    .replace(/\s+/gu, " ")
    .trim()
    .slice(0, maxLength)
    .trim()
  return cleaned || fallback
}

/** Normalize user-facing metadata before placing it in YAML or registry JSON. */
export function sanitizeThemeName(value: string): string {
  return cleanText(value, DEFAULT_NAME, 80)
}

export function sanitizeThemeDescription(value?: string): string {
  return cleanText(value ?? DEFAULT_DESCRIPTION, DEFAULT_DESCRIPTION, 240)
}

function yamlString(value: string): string {
  // JSON strings are valid YAML double-quoted scalars and escape control syntax
  // deterministically without adding another YAML dependency to the client.
  return JSON.stringify(value)
}

export interface DesignMdOptions {
  name: string
  description?: string
  radius: string
  /** Direct exports follow the selected format. Installed files use OKLCH. */
  format?: ColorFormat
}

/** Serialize one complete ThemeLab theme into Google's alpha DESIGN.md format. */
export function themeStylesToDesignMd(
  theme: ThemeStyles,
  options: DesignMdOptions
): string {
  const name = sanitizeThemeName(options.name)
  const description = sanitizeThemeDescription(options.description)
  const format = options.format ?? "oklch"
  const colorLines: string[] = []

  for (const token of THEME_TOKENS) {
    const value = theme.light[token]
    if (value != null)
      colorLines.push(`  ${token}: ${yamlString(reformat(value, format))}`)
  }
  for (const token of THEME_TOKENS) {
    const value = theme.dark[token]
    if (value != null)
      colorLines.push(`  dark-${token}: ${yamlString(reformat(value, format))}`)
  }

  return [
    "---",
    "version: alpha",
    `name: ${yamlString(name)}`,
    `description: ${yamlString(description)}`,
    "colors:",
    ...colorLines,
    "rounded:",
    `  base: ${yamlString(options.radius)}`,
    "---",
    "",
    `# ${name}`,
    "",
    "## Overview",
    "",
    `This document records the shadcn semantic color tokens and base corner radius for ${name}. It defines separate light and dark color modes.`,
    "",
    "## Colors",
    "",
    "Light-mode colors use the canonical shadcn token names. Dark-mode equivalents use the same names with a `dark-` prefix.",
    "",
    "## Shapes",
    "",
    `The configured base corner radius is \`${options.radius}\`, exposed as \`rounded.base\`.`,
    "",
    "## Components",
    "",
    "Components use each color token according to its shadcn semantic role. In dark mode, use the corresponding `dark-*` token for that role.",
    "",
    "## Do's and Don'ts",
    "",
    "- Do use canonical tokens for light mode and their `dark-*` equivalents for dark mode.",
    "- Do use `rounded.base` as the configured base corner radius.",
    "- Don't substitute one semantic color role for another.",
    "- Don't combine light-mode and dark-mode token values in the same mode.",
    "",
  ].join("\n")
}
