import { decodeInstallPayload } from "./install-payload"
import {
  reformat,
  THEME_TOKENS,
  themeStylesToDesignMd,
} from "@themelab/theme-engine"

const REGISTRY_SCHEMA = "https://ui.shadcn.com/schema/registry.json"
const REGISTRY_ITEM_SCHEMA = "https://ui.shadcn.com/schema/registry-item.json"

function registryName(name: string): string {
  const slug = name
    .normalize("NFKD")
    .replaceAll(/[\u0300-\u036F]/gu, "")
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/gu, "-")
    .replaceAll(/^-+|-+$/gu, "")
    .slice(0, 64)
    .replace(/-+$/u, "")
  return slug || "themelab-theme"
}

export function createRegistryCatalog() {
  return {
    $schema: REGISTRY_SCHEMA,
    name: "ThemeLab",
    homepage: "https://themelab.dev",
    items: [],
  }
}

export function installPayloadToRegistryItem(payload: string) {
  const decoded = decodeInstallPayload(payload)
  const light: Record<string, string> = { radius: decoded.radius }
  const dark: Record<string, string> = {}

  for (const token of THEME_TOKENS) {
    light[token] = reformat(decoded.theme.light[token], "oklch")
    dark[token] = reformat(decoded.theme.dark[token], "oklch")
  }

  return {
    $schema: REGISTRY_ITEM_SCHEMA,
    name: registryName(decoded.name),
    type: "registry:theme" as const,
    title: decoded.name,
    description: `A complete light and dark shadcn theme generated by ThemeLab.`,
    cssVars: { light, dark },
    files: [
      {
        path: "DESIGN.md",
        type: "registry:file" as const,
        target: "~/DESIGN.md",
        content: themeStylesToDesignMd(decoded.theme, {
          name: decoded.name,
          description:
            "A shadcn theme generated by ThemeLab with light and dark semantic color tokens.",
          radius: decoded.radius,
          format: "oklch",
        }),
      },
    ],
  }
}
